services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Timiki\Bundle\RpcServerBundle\Controller\:
        resource: '%kernel.project_dir%/src/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]